
name: SpringBoot Deployment Github Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Compile The Project
      run: mvn compile
    - name: Run the Unit Test
      run: mvn test
    - name: Package War
      run: mvn package

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        # Artifact name
        name: Ecomm War Artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: target/*.war
        if-no-files-found: warn # optional, default is warn
        retention-days: 30 # optional, default is 30
        compression-level: 6 # optional, default is 6
        overwrite: true # optional, default is false
    - name: Deploy to Tomcat
      env:
        TOMCAT_USER: admin
        TOMCAT_PASSWORD: admin
        TOMCAT_HOST: 3.110.102.121
        TOMCAT_PORT: 8085
      run: |
        WAR_FILE=$(ls target/*.war)
        curl --upload-file "$WAR_FILE" "http://${{ env.TOMCAT_USER }}:${{ env.TOMCAT_PASSWORD }}@${{ env.TOMCAT_HOST }}:${{ env.TOMCAT_PORT }}/manager/text/deploy?path=/JtSpringProject&update=true"

    
